version: '3.8'
services:
  core:
    build: .
    ports:
      - "8501:8501"
    environment:
      - PORT=8501
      - STREAMLIT_SERVER_ENABLECORS=false
      # секреты через env vars или docker secrets
      # - SENTRY_DSN=${SENTRY_DSN}
    volumes:
      - ./:/app:rw

  # optional: postgres for Supabase-like local testing
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scenario_leads
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: