name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # ИЗМЕНЕНО: Добавляем установку зависимостей для разработки
          pip install -r requirements-dev.txt
      - name: Check formatting with black
        run: |
          black --check .
      - name: Run tests
        run: |
          pytest